// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// THIS FILE IS AUTOGENERATED. DO NOT EDIT MANUALLY.

//! Default Python distributions.

use crate::py_packaging::distribution::{
    PythonDistributionLocation, PythonDistributionRecord,
};
use crate::python_distributions::PythonDistributionCollection;
use once_cell::sync::Lazy;

pub static PYTHON_DISTRIBUTIONS: Lazy<PythonDistributionCollection> = Lazy::new(|| {
    let dists = vec![
        // Linux glibc linked.
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.9.21%2B20250106-aarch64-unknown-linux-gnu-noopt-full.tar.zst".to_string(),
                sha256: "90055e1582242088b919f50f783fddee556ed5969f88acddd401e5b56c397f15".to_string(),
            },
            target_triple: "aarch64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.9.21%2B20250106-x86_64-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "6ab5494c55f06be1501610e504dab177217a4a79466e8e0edce4a7f6c7840d85".to_string(),
            },
            target_triple: "x86_64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.9.21%2B20250106-x86_64_v2-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "0995db9a71ed4cd0643befd72396732c383a3386274c2ba33651bf243b825c83".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.9.21%2B20250106-x86_64_v3-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "2b8da9dad6c3920e24360133b67c342ae8be9169a277913236017a3331768320".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.10.16%2B20250106-aarch64-unknown-linux-gnu-noopt-full.tar.zst".to_string(),
                sha256: "ee1e7dce9bd8cb920448315a551e53f8315f8efdf661ecb93dd3f7a5ff3efef5".to_string(),
            },
            target_triple: "aarch64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.10.16%2B20250106-x86_64-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "060adc81f4ce2243a48750d3e6b53c660ea3e367fc2758b53db3c83c5f8be5ab".to_string(),
            },
            target_triple: "x86_64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.10.16%2B20250106-x86_64_v2-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "09f1e66a5d49112e7b111bdd3371d8c484a33a17a7f1d8fc63fecf84663ec12b".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.10.16%2B20250106-x86_64_v3-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "9a1827969ad487b2bb351211de300116ab0565ef93caa7e30751c40e91cbf4f8".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.11.11%2B20250106-aarch64-unknown-linux-gnu-noopt-full.tar.zst".to_string(),
                sha256: "d44c69f0ad88b7490cf29f36f2e3c0ea9d8b0c781f10f2359fcf7b68166d0d26".to_string(),
            },
            target_triple: "aarch64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.11.11%2B20250106-x86_64-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "82119b650e3998269b3c79d443a0a1f756ce95f0b86988f18c3c22b019a9c716".to_string(),
            },
            target_triple: "x86_64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.11.11%2B20250106-x86_64_v2-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "f93a4b5cef9d5d8be8dcf9b217685defe3e8a381bb92b4dfc58c53fce01628b9".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.11.11%2B20250106-x86_64_v3-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "194ed2f6c621f73b0a1f25238f01729759909421a6c841b0dba0016791838f7b".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.12.8%2B20250106-aarch64-unknown-linux-gnu-noopt-full.tar.zst".to_string(),
                sha256: "e0afae2fa208f853f332b2cf8d1ea57227d0edd187ea4d37e9767713919e9fbd".to_string(),
            },
            target_triple: "aarch64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.12.8%2B20250106-x86_64-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "6d29d5f90fdaaeef76580e1271ccf43d187a158dfde6f2c08a321fa6f1f3eb54".to_string(),
            },
            target_triple: "x86_64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.12.8%2B20250106-x86_64_v2-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "dafad4b345e1a6044dd94324e612b473a9c8b90e3f24105db91601482d624362".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.12.8%2B20250106-x86_64_v3-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "bf26baa71facdf0d2fab4bcd833ea58c31e1c6e1f56cec36f60efbbc9586516a".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.13.1%2B20250106-aarch64-unknown-linux-gnu-noopt-full.tar.zst".to_string(),
                sha256: "0a511e849d4d1e6ccf71f74d832f94c45f2583d89ad7608ae611ac040f76759c".to_string(),
            },
            target_triple: "aarch64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.13.1%2B20250106-x86_64-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "a60a57134160030bf4c1ad21686665234e00d6575d48a67675882a050e1f7f14".to_string(),
            },
            target_triple: "x86_64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.13.1%2B20250106-x86_64_v2-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "71a441477bb2d564d975948c0b686510ecb30569aab495c62354b4797590edcb".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.13.1%2B20250106-x86_64_v3-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "063558065ea09397fe822b595cd7bc27ba3090a3e12882a24969fcec26cd7ba1".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },

        // Linux musl.
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.9.21%2B20250106-x86_64-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "376a73b9ccf30894f293a780a1f725c477abb104e2cd435239628b796d90f376".to_string(),
            },
            target_triple: "x86_64-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: false,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.9.21%2B20250106-x86_64_v2-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "21e035abe008337817bfe637115cb2d26aae768d11ac9bd342f3bae5593f8b38".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.9.21%2B20250106-x86_64_v3-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "3602074470d765f47d5723651f78612241e5107221447419a0ddb03faaee02c9".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.10.16%2B20250106-x86_64-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "64c094f1cc234b27af73921fa4eb92cf297eb924cc3c78460bc2041fe745b9a1".to_string(),
            },
            target_triple: "x86_64-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: false,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.10.16%2B20250106-x86_64_v2-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "2f4892162d45b97ccd68806f352617ece46ad812cda93a7db52f240498be7338".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.10.16%2B20250106-x86_64_v3-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "5ab3bd07721d86abaaef26ca2f87eb2ef7e7d69f076d50ca3d70915dbdb88bf6".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.11.11%2B20250106-x86_64-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "39654ea495c2ce891259589610956cf0b5d790566eb4bc3217dcbb3a88781f2b".to_string(),
            },
            target_triple: "x86_64-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: false,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.11.11%2B20250106-x86_64_v2-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "79de286e5167c19ec41bcfc9e109d11293bb7794962212361a4d7ff80a87c56b".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.11.11%2B20250106-x86_64_v3-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "28d8097724b44888a8c4be04867ca6bb71a1bc2bef554cc40e5f19688600a8f4".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.12.8%2B20250106-x86_64-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "c63156572a54d9dc1385d1e973342db466c3587fac75fb9c980248872dc87e57".to_string(),
            },
            target_triple: "x86_64-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: false,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.12.8%2B20250106-x86_64_v2-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "9757243f6daa983c0790ba37dadc515caf9b4672bf3ecd416f43828d605cb365".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.12.8%2B20250106-x86_64_v3-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "9231c8ac24e362ae4b0ef28e6a71557a78bc715b46f5eda64f7b73f7fc10d85a".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.13.1%2B20250106-x86_64-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "2a8fb81fb33b8113e797d0960f90467cdb3961076e7a75b99b26348f09ee18bd".to_string(),
            },
            target_triple: "x86_64-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: false,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.13.1%2B20250106-x86_64_v2-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "9e0724ff5fa2b44a4cab9477378a38719bc2601c0bfada76a024437222d57233".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.13.1%2B20250106-x86_64_v3-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "f274dc865eed5c33296d988426b36d3b73bb0d987c5a7a88e612aff7544c9ccc".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },

        // The order here is important because we will choose the
        // first one. We prefer shared distributions on Windows because
        // they are more versatile: statically linked Windows distributions
        // don't declspec(dllexport) Python symbols and can't load shared
        // shared library Python extensions, making them a pain to work
        // with.

        // Windows shared.
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.9.21%2B20250106-i686-pc-windows-msvc-shared-pgo-full.tar.zst".to_string(),
                sha256: "18c9af3c4eb7d95b0c3ded45702f0351f8524654f77339ac3851fe9f112bd3d2".to_string(),
            },
            target_triple: "i686-pc-windows-msvc".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.10.16%2B20250106-i686-pc-windows-msvc-shared-pgo-full.tar.zst".to_string(),
                sha256: "8e449d3bfd3cba4499528936402d3d8379dfbd353fa93b2dd50f754d51cb35ec".to_string(),
            },
            target_triple: "i686-pc-windows-msvc".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.11.11%2B20250106-i686-pc-windows-msvc-shared-pgo-full.tar.zst".to_string(),
                sha256: "fd15f005af6dc60436300188bbd277a3937f66662fb68f9b6d78309542d228f0".to_string(),
            },
            target_triple: "i686-pc-windows-msvc".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.12.8%2B20250106-i686-pc-windows-msvc-shared-pgo-full.tar.zst".to_string(),
                sha256: "764c1063a0dff63e92b00cc5622ca13297d9921d7577c00695cbd52f74a51df4".to_string(),
            },
            target_triple: "i686-pc-windows-msvc".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.13.1%2B20250106-i686-pc-windows-msvc-shared-pgo-full.tar.zst".to_string(),
                sha256: "1e22fafd2723b19e3f0af1ec171d235d58badae75adc3669383795a2fbbdb5db".to_string(),
            },
            target_triple: "i686-pc-windows-msvc".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.9.21%2B20250106-x86_64-pc-windows-msvc-shared-pgo-full.tar.zst".to_string(),
                sha256: "dd8943846c06ce9f65600376279711da2159181bde1516a332e840104df20dfb".to_string(),
            },
            target_triple: "x86_64-pc-windows-msvc".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.10.16%2B20250106-x86_64-pc-windows-msvc-shared-pgo-full.tar.zst".to_string(),
                sha256: "41804f4cf44f175b2184fb6d33b65c3d94dde4d7643fcdae7b473992a01dfdd6".to_string(),
            },
            target_triple: "x86_64-pc-windows-msvc".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.11.11%2B20250106-x86_64-pc-windows-msvc-shared-pgo-full.tar.zst".to_string(),
                sha256: "1e6ce41ad38cd0940c874020345fbb43c3ef23fa9b5bf16f41f7c2fea49d97ae".to_string(),
            },
            target_triple: "x86_64-pc-windows-msvc".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.12.8%2B20250106-x86_64-pc-windows-msvc-shared-pgo-full.tar.zst".to_string(),
                sha256: "ca9ecf9309db7f909f8ff59dc4549b67bbd33ebb6e77a6738d648674353c9ce7".to_string(),
            },
            target_triple: "x86_64-pc-windows-msvc".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.13.1%2B20250106-x86_64-pc-windows-msvc-shared-pgo-full.tar.zst".to_string(),
                sha256: "46d782865407c8fbf23ea8d44b58fcd1f5fb885f408c670bc82d195feb12e407".to_string(),
            },
            target_triple: "x86_64-pc-windows-msvc".to_string(),
            supports_prebuilt_extension_modules: true,
        },

        // Windows static.
        // DEPRECATED

        // macOS.
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.9.21%2B20250106-aarch64-apple-darwin-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "1dc5cb57c106b2aef01d7bfa95d431ebbb721a74573152556a620eac7bf1a659".to_string(),
            },
            target_triple: "aarch64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.10.16%2B20250106-aarch64-apple-darwin-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "8a66f333af31fa888e0ee3b678734458a145251c6c26b4dfa7b818d891b5ffc4".to_string(),
            },
            target_triple: "aarch64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.11.11%2B20250106-aarch64-apple-darwin-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "ad2d011dc474915c3ccf5069185957afc7dcd855b05b6aed259eb5bb467fdf86".to_string(),
            },
            target_triple: "aarch64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.12.8%2B20250106-aarch64-apple-darwin-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "c5630f504482780b9c15dac0a7b39c1e52e12e86a14d2a8852fac222f2a9336b".to_string(),
            },
            target_triple: "aarch64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.13.1%2B20250106-aarch64-apple-darwin-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "16998853421d009d9df6ed0a4a447517eeaec1699c9d2b56f3f8a76611f95912".to_string(),
            },
            target_triple: "aarch64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.9.21%2B20250106-x86_64-apple-darwin-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "3f40805ac589b2d99530642c5b152608f65c6386a06276f2f85bc9d5c6393c79".to_string(),
            },
            target_triple: "x86_64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.10.16%2B20250106-x86_64-apple-darwin-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "99356bd0d9c439f3823c6bbe3c51ad5adf199f644243c4caa5c24d510b012527".to_string(),
            },
            target_triple: "x86_64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.11.11%2B20250106-x86_64-apple-darwin-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "37531c7c923bcf6f7465cc1c2280ea3d25177c3d791982b537eec038e9e1baee".to_string(),
            },
            target_triple: "x86_64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.12.8%2B20250106-x86_64-apple-darwin-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "0cfaf59e0fb13def06a0e6ccf06708569bb530cf02a70352dd62f24dfd653447".to_string(),
            },
            target_triple: "x86_64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250106/cpython-3.13.1%2B20250106-x86_64-apple-darwin-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "89f49a5d2127053abb3fb1f1f4d2705764cf278b0b3f1e79507e7e0d3a8a01a8".to_string(),
            },
            target_triple: "x86_64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
    ];

    PythonDistributionCollection { dists }
});
