// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// THIS FILE IS AUTOGENERATED. DO NOT EDIT MANUALLY.

//! Default Python distributions.

use crate::py_packaging::distribution::{
    PythonDistributionLocation, PythonDistributionRecord,
};
use crate::python_distributions::PythonDistributionCollection;
use once_cell::sync::Lazy;

pub static PYTHON_DISTRIBUTIONS: Lazy<PythonDistributionCollection> = Lazy::new(|| {
    let dists = vec![
        // Linux glibc linked.
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.9.22%2B20250409-aarch64-unknown-linux-gnu-noopt-full.tar.zst".to_string(),
                sha256: "396057bf0e293b92d182b08389806257c6691605d8055968ca7b85b71dd8da0d".to_string(),
            },
            target_triple: "aarch64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.9.22%2B20250409-x86_64-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "ac71f612cb9210968424f41c3afb523a6cce0c3fc17aee0807a00dce9076be77".to_string(),
            },
            target_triple: "x86_64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.9.22%2B20250409-x86_64_v2-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "34a93a314fcec78b69a44c1ac8a46b42c025ae7a8e8d677b315cb5a91122b444".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.9.22%2B20250409-x86_64_v3-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "71d603870b702b0f9d26e69aa20189e4bb59b2ea72727f438a3f04cbc3de094b".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.10.17%2B20250409-aarch64-unknown-linux-gnu-noopt-full.tar.zst".to_string(),
                sha256: "338e6be49e7bd0474e0081bacc9ea92b2dabf0c4af56777ce17e71e97a941ca6".to_string(),
            },
            target_triple: "aarch64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.10.17%2B20250409-x86_64-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "b29cd5244fe43a3464c77a30a8099d3d8fd997b16c0edd75ac4cacd4e825efba".to_string(),
            },
            target_triple: "x86_64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.10.17%2B20250409-x86_64_v2-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "3ca1b8715ef47d11b63fba04d34b42197fb5aa2b7e99729eea85aa4b9260fc04".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.10.17%2B20250409-x86_64_v3-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "c46a430591db96ae8239db2f3f28767744e6e93a075b1c9a7f72dbb6702f2406".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.11.12%2B20250409-aarch64-unknown-linux-gnu-noopt-full.tar.zst".to_string(),
                sha256: "11ac1a56e1f0aeb6d214d1f403d6af9e48fe4b727913322fc591a13ae24985df".to_string(),
            },
            target_triple: "aarch64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.11.12%2B20250409-x86_64-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "fe243d83d58470d4a463899b3e924a9f04145dbf75ea7d37e596cac273ee5ca4".to_string(),
            },
            target_triple: "x86_64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.11.12%2B20250409-x86_64_v2-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "68a3c1c39e9c69c2c89104eef725024cbf5f46acf955eeb28045c7c80814b124".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.11.12%2B20250409-x86_64_v3-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "97e577b94f3b14d2ff4d26c476c58933f58c239c0ba344df3d1f44b293b130bc".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.11.12%2B20250409-x86_64_v4-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "242b174e8b5ea7907f7f2b772962589d90abd923fda4aab73bd6a27b8b3735df".to_string(),
            },
            target_triple: "x86_64_v4-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.12.10%2B20250409-aarch64-unknown-linux-gnu-noopt-full.tar.zst".to_string(),
                sha256: "b8627722f547d1947aed38ecef5127f7c4e76300b58097727e56f3774a7c2096".to_string(),
            },
            target_triple: "aarch64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.12.10%2B20250409-x86_64-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "ddbb161ab3bfe45900880ef984c854c4421339d474aeb9862f0d86dd8c4d37ed".to_string(),
            },
            target_triple: "x86_64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.12.10%2B20250409-x86_64_v2-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "ee3bfa56fdbf2646824ae5699de18cd44445c5aeb035a33e6ea187b8157b7273".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.12.10%2B20250409-x86_64_v3-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "1564956fc3dfdad1f421c3786eb2ef68731a7b3d2a5d723ae38a3f5b4412219b".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.12.10%2B20250409-x86_64_v4-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "ec4b0d1683489d2f58c944510806238ef3d930d5eef5ddd50f3b2139ae9d749f".to_string(),
            },
            target_triple: "x86_64_v4-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.13.3%2B20250409-aarch64-unknown-linux-gnu-noopt-full.tar.zst".to_string(),
                sha256: "61fa7a1f29562f2b59643257b44201b787152ef3284a0ba6a2090c855df0f9a4".to_string(),
            },
            target_triple: "aarch64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.13.3%2B20250409-x86_64-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "6d70a399fb4e1f3ac423d4b208a77dd95583a51808a95ae089e091bfb983f988".to_string(),
            },
            target_triple: "x86_64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.13.3%2B20250409-x86_64_v2-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "9062abe8609ee4e073a40eaabfc8cb955bb2bc5ba3132da7d9c83fe7bea61d27".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.13.3%2B20250409-x86_64_v3-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "f6ec45836472a72ad01b47c8c65dc65fb299de36f01b46c5bafec400d45fbe0e".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.13.3%2B20250409-x86_64_v4-unknown-linux-gnu-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "0760577dfea93c6308581b6bf95a60039e15df1a0d0c55390dc74fc856225edb".to_string(),
            },
            target_triple: "x86_64_v4-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },

        // Linux musl.
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.9.22%2B20250409-x86_64-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "43f16f46a9c12efc2f097541901e78ab1f185bfd07d1421c3157c3e27993c25f".to_string(),
            },
            target_triple: "x86_64-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: false,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.9.22%2B20250409-x86_64-unknown-linux-musl-lto-full.tar.zst".to_string(),
                sha256: "ca101d3e5245445b1588440f20c91aa4414e12da403d60e79421a58464def1e4".to_string(),
            },
            target_triple: "x86_64-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: false,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.9.22%2B20250409-x86_64_v2-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "cd370677f4c3555e7a78a3921c3a89dc05e4620be32fbfce4dffe67f30a387a6".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.9.22%2B20250409-x86_64_v2-unknown-linux-musl-lto-full.tar.zst".to_string(),
                sha256: "8dcc0a98d2f34e4ad238d676221df78a70592c9851b43534aabaa79c107b86d4".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.9.22%2B20250409-x86_64_v3-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "8ecf840f8d7c02dcff2d3e1811b9d1367aa8317317a2ecbc902b322e275e6404".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.9.22%2B20250409-x86_64_v3-unknown-linux-musl-lto-full.tar.zst".to_string(),
                sha256: "89cbd55848f63baf4fa4995f95dcbbefbba79fa3e46b1639ae7d08352bb14428".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.10.17%2B20250409-x86_64-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "3cb3a2867dfd9dea79d5328efa8c092082f3c3820f0180b4ee1341feb31c7303".to_string(),
            },
            target_triple: "x86_64-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: false,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.10.17%2B20250409-x86_64-unknown-linux-musl-lto-full.tar.zst".to_string(),
                sha256: "2bdd5e1ecc6f178a92f9b55bfa9e6921d9d8e92898b9be69ec508aee107ab2e4".to_string(),
            },
            target_triple: "x86_64-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: false,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.10.17%2B20250409-x86_64_v2-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "6ca3792b692d6001be564ed3ec6fdb2853234b5ecaf40d315038ced5b9c4a297".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.10.17%2B20250409-x86_64_v2-unknown-linux-musl-lto-full.tar.zst".to_string(),
                sha256: "ec9ed229f1d01aac53ac83342ca1dcf811be9596e27d0f8a2017f7f1a3976bda".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.10.17%2B20250409-x86_64_v3-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "9359e47fd71085066303e8aed089c7dd905ecb7c4f6b49e5bb4a3188797d1f44".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.10.17%2B20250409-x86_64_v3-unknown-linux-musl-lto-full.tar.zst".to_string(),
                sha256: "f5547feb9977d67fe5b37b53c10e6fb63931137d4ba1dad63e98ec277a887f8b".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.11.12%2B20250409-x86_64-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "fef79e277941a9212ad77aab395b65910178af0100b666f68d82a274b00f1090".to_string(),
            },
            target_triple: "x86_64-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: false,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.11.12%2B20250409-x86_64-unknown-linux-musl-lto-full.tar.zst".to_string(),
                sha256: "e1ac104291f8c2bcb43f56c283a58e9bee57761568466192759a4ce18f09ec24".to_string(),
            },
            target_triple: "x86_64-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: false,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.11.12%2B20250409-x86_64_v2-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "29544026a56c1609023ee6a1c3f46bdc9f6a6dd1212576f6e68ff0fe81ea57c5".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.11.12%2B20250409-x86_64_v2-unknown-linux-musl-lto-full.tar.zst".to_string(),
                sha256: "472a66f1c70a2bdaf65ec3e6c236bf18c080fba21b15154f3ec55480f3638516".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.11.12%2B20250409-x86_64_v3-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "b0fc35defac82f24b01eb33338f6fb81504f2d95b9e1e83ef6b2b648c3742af2".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.11.12%2B20250409-x86_64_v3-unknown-linux-musl-lto-full.tar.zst".to_string(),
                sha256: "d23f65528c8b4a56e12bc3530abec9d2813375e47672ce2518b0ee2e1a935818".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.11.12%2B20250409-x86_64_v4-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "b60dcf856a9756086d82d365f6b2cb11d47d95f97fe8030b99cafed570c261cb".to_string(),
            },
            target_triple: "x86_64_v4-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.11.12%2B20250409-x86_64_v4-unknown-linux-musl-lto-full.tar.zst".to_string(),
                sha256: "a9d978f0c4a0a8bc181b04de40c80e2b72f79808d8fb5d3d8cb4d77dfd8ea896".to_string(),
            },
            target_triple: "x86_64_v4-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.12.10%2B20250409-x86_64-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "7c4535e0348efdcb6a6567d03a8bde7915341d0092c74aea0f908c7e796c5553".to_string(),
            },
            target_triple: "x86_64-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: false,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.12.10%2B20250409-x86_64-unknown-linux-musl-lto-full.tar.zst".to_string(),
                sha256: "1b6a27980e064ff0345d4526536e5b43cea36a8242429f8c5671ddb44d3ffc00".to_string(),
            },
            target_triple: "x86_64-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: false,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.12.10%2B20250409-x86_64_v2-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "1abd65c6a67dc97cb68e5762131931100b194e13dff968301702e44c07372f2a".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.12.10%2B20250409-x86_64_v2-unknown-linux-musl-lto-full.tar.zst".to_string(),
                sha256: "f6bba32101523cddb8f76a0bc9ad11de19b76245a17516ae687292dbac6237b9".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.12.10%2B20250409-x86_64_v3-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "9f7b0529a2fd5d56ca14df649a108661fe12031543afd7b659969a01b4e35be5".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.12.10%2B20250409-x86_64_v3-unknown-linux-musl-lto-full.tar.zst".to_string(),
                sha256: "62a5d024ab2b171b34786b643e146602bdf8e0ab9fbbd6ad65cf148654d68cfd".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.12.10%2B20250409-x86_64_v4-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "ea2336420a2e2768e7755d33897015ce9fc2216adf8607ea6dd6c4bab2f65824".to_string(),
            },
            target_triple: "x86_64_v4-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.12.10%2B20250409-x86_64_v4-unknown-linux-musl-lto-full.tar.zst".to_string(),
                sha256: "0ed4b0f21716e30487b254ef1e17e92b749abe8a5875161ec8feb55db5dba9c0".to_string(),
            },
            target_triple: "x86_64_v4-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.13.3%2B20250409-x86_64-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "740e3479ed9ab1a11902fe408cb77556ab5a583ead241fbbb7420e5ad2d34333".to_string(),
            },
            target_triple: "x86_64-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: false,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.13.3%2B20250409-x86_64-unknown-linux-musl-lto-full.tar.zst".to_string(),
                sha256: "7bf8f6d804c12cdbae784d873e4b53ab353be7460e8a25b883761ab7c8c17df7".to_string(),
            },
            target_triple: "x86_64-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: false,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.13.3%2B20250409-x86_64_v2-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "45dc6c59828dfac8c3027798e78c2c4c6afe47106a19585551332a61949bb8df".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.13.3%2B20250409-x86_64_v2-unknown-linux-musl-lto-full.tar.zst".to_string(),
                sha256: "5a395bd18574bd6bf2d51ed56c8138c62cc97d1576ef65f0ff33489bb40c249e".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.13.3%2B20250409-x86_64_v3-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "81b2b2eae1c6f8103adb924308bf1802864f65238de30b3f425a593ee7bcd982".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.13.3%2B20250409-x86_64_v3-unknown-linux-musl-lto-full.tar.zst".to_string(),
                sha256: "112179184a18f5f3067e531ef95add59b61cd0244a83a2d2c520f8b202d7af32".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.13.3%2B20250409-x86_64_v4-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "a58b6fbfa3adcb5d70ae0995371c57d0fba296517197fcfbdde0df3a9828ef0f".to_string(),
            },
            target_triple: "x86_64_v4-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.13.3%2B20250409-x86_64_v4-unknown-linux-musl-lto-full.tar.zst".to_string(),
                sha256: "d018b1145d68984409807786360a829e3274aefc79d350e731a51cecefdfea75".to_string(),
            },
            target_triple: "x86_64_v4-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },

        // The order here is important because we will choose the
        // first one. We prefer shared distributions on Windows because
        // they are more versatile: statically linked Windows distributions
        // don't declspec(dllexport) Python symbols and can't load shared
        // shared library Python extensions, making them a pain to work
        // with.

        // Windows shared.
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.9.22%2B20250409-i686-pc-windows-msvc-pgo-full.tar.zst".to_string(),
                sha256: "1eb96550beaa44148dc7aa796e0bcb649bb4af71d89ed28e4019ed1f28b05d2f".to_string(),
            },
            target_triple: "i686-pc-windows-msvc".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.10.17%2B20250409-i686-pc-windows-msvc-pgo-full.tar.zst".to_string(),
                sha256: "f7552299367cface6922e5a26b625da1ef55bd98a489003054b511999f8bc57c".to_string(),
            },
            target_triple: "i686-pc-windows-msvc".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.11.12%2B20250409-i686-pc-windows-msvc-pgo-full.tar.zst".to_string(),
                sha256: "f3f01682b1f17a4ee89c9423c7210b4082a1c305ea63d7df2c5dc5a97bfbcf3d".to_string(),
            },
            target_triple: "i686-pc-windows-msvc".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.12.10%2B20250409-i686-pc-windows-msvc-pgo-full.tar.zst".to_string(),
                sha256: "d22e1d99d4ff68aec3cf3b587a7e1b71f11743c53e61bcd78ecb305e8a31ff2a".to_string(),
            },
            target_triple: "i686-pc-windows-msvc".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.13.3%2B20250409-i686-pc-windows-msvc-pgo-full.tar.zst".to_string(),
                sha256: "2763c4dab1c6f71f5354d0e854bd70f593e1edf51f5ec9c159a866c9eab06e0e".to_string(),
            },
            target_triple: "i686-pc-windows-msvc".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.9.22%2B20250409-x86_64-pc-windows-msvc-pgo-full.tar.zst".to_string(),
                sha256: "6733967b9bdb626fc5cc70fe2cc8be796b2069abd189892ae8e694c2641efca1".to_string(),
            },
            target_triple: "x86_64-pc-windows-msvc".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.12.10%2B20250409-x86_64-pc-windows-msvc-pgo-full.tar.zst".to_string(),
                sha256: "4ef84ccf5a095fd95ab6662244fbcb8b022f2ffa6c74779385fb825a3db42b6b".to_string(),
            },
            target_triple: "x86_64-pc-windows-msvc".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.13.3%2B20250409-x86_64-pc-windows-msvc-pgo-full.tar.zst".to_string(),
                sha256: "6f1f75ba719d30a65941c196e0fd51aa16831b508654ffed61e3dd3c922b9391".to_string(),
            },
            target_triple: "x86_64-pc-windows-msvc".to_string(),
            supports_prebuilt_extension_modules: true,
        },

        // Windows static.
        // Removed, see https://github.com/astral-sh/python-build-standalone/issues/221
        // macOS.
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.9.22%2B20250409-aarch64-apple-darwin-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "2adf173bdb7f6ae0e100ecdf3d5d39cb87752611db7404552f80d86ac679040a".to_string(),
            },
            target_triple: "aarch64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.10.17%2B20250409-aarch64-apple-darwin-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "3dc1f0249dc9f2cffb49c1e71c7d0142c159d203ca499341c162bd0485450fec".to_string(),
            },
            target_triple: "aarch64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.11.12%2B20250409-aarch64-apple-darwin-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "f17c56473a5d2fa169dca335e798fa16ec9e242190a622e026c2ba100c3c55c9".to_string(),
            },
            target_triple: "aarch64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.12.10%2B20250409-aarch64-apple-darwin-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "f18cc4c89ae736b71b27f4a998f4b117a0eb329048548ebffed7fe1b867e225c".to_string(),
            },
            target_triple: "aarch64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.13.3%2B20250409-aarch64-apple-darwin-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "2195b029814d5fefe47b0b9925d09dc08d120124510e75e9294eb6885755dc5d".to_string(),
            },
            target_triple: "aarch64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.9.22%2B20250409-x86_64-apple-darwin-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "c606731c2804225f629990b39ac6a97dceeffe2b1a8e05fd2a0f726f3e0a1781".to_string(),
            },
            target_triple: "x86_64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.10.17%2B20250409-x86_64-apple-darwin-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "8a18fa1a536baadbb91b172cac1aa170c0ac10ba462ded65c596bca9a868f0c4".to_string(),
            },
            target_triple: "x86_64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.11.12%2B20250409-x86_64-apple-darwin-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "63023f049ae4384e9d2d30ccca42bdf60d0d883f4149b6f7cec2320568f01c10".to_string(),
            },
            target_triple: "x86_64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.12.10%2B20250409-x86_64-apple-darwin-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "5b0af42fb040ac890c9f0716a899e92d6465a83a40cfbd15376bfca16089b224".to_string(),
            },
            target_triple: "x86_64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.13.3%2B20250409-x86_64-apple-darwin-pgo%2Blto-full.tar.zst".to_string(),
                sha256: "88eb874ee1c75ae6cf3975e68d40b3f51de7d0fdb9d67b2f8a5505c849a206b3".to_string(),
            },
            target_triple: "x86_64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
    ];

    PythonDistributionCollection { dists }
});
