// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// THIS FILE IS AUTOGENERATED. DO NOT EDIT MANUALLY.

//! Default Python distributions.

use crate::py_packaging::distribution::{
    PythonDistributionLocation, PythonDistributionRecord,
};
use crate::python_distributions::PythonDistributionCollection;
use once_cell::sync::Lazy;

pub static PYTHON_DISTRIBUTIONS: Lazy<PythonDistributionCollection> = Lazy::new(|| {
    let dists = vec![
        // Linux glibc linked.
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.9.21%2B20241206-aarch64-unknown-linux-gnu-noopt-full.tar.zst".to_string(),
                sha256: "6ad6385226be7b195ec2eca81004a971cea384924e78bf71d51333eb679c29d7".to_string(),
            },
            target_triple: "aarch64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.9.21%2B20241206-x86_64-unknown-linux-gnu-pgo-full.tar.zst".to_string(),
                sha256: "59cc4ee05b10127141b53e86a188428eea9b40d1e198c0cb2c3898b715e802de".to_string(),
            },
            target_triple: "x86_64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.9.21%2B20241206-x86_64_v2-unknown-linux-gnu-pgo-full.tar.zst".to_string(),
                sha256: "a06024bf29b4f70e5e93996095fe98928267e89fafb5402cdb47492cdcf266a1".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.9.21%2B20241206-x86_64_v3-unknown-linux-gnu-pgo-full.tar.zst".to_string(),
                sha256: "0a7d397d70c22474fa6f515fa721f3ab327c837a49bbee6e991f8be45f69814e".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.10.16%2B20241206-aarch64-unknown-linux-gnu-noopt-full.tar.zst".to_string(),
                sha256: "dae7c922f893740fac1c91617525a03ba536563012dd30a4fe0cbecbdb3878ee".to_string(),
            },
            target_triple: "aarch64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.10.16%2B20241206-x86_64-unknown-linux-gnu-pgo-full.tar.zst".to_string(),
                sha256: "af723dab5e18a0bb51376d0300d7fec0fa3c3bcb641ed984e92473fbcbeab1fc".to_string(),
            },
            target_triple: "x86_64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.10.16%2B20241206-x86_64_v2-unknown-linux-gnu-pgo-full.tar.zst".to_string(),
                sha256: "0c18ce30cbed7bc530d51be7ba51f1dd0ddaf05d6530a95fe4d313f942806110".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.10.16%2B20241206-x86_64_v3-unknown-linux-gnu-pgo-full.tar.zst".to_string(),
                sha256: "180d3b1b87b83fd05670a0816e7a255e55d6e025572b9e31fdfc940557781f1c".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.11.11%2B20241206-aarch64-unknown-linux-gnu-noopt-full.tar.zst".to_string(),
                sha256: "5db3ccc467cf2fa08c49f68eedc325d7d8c444e88b67cffce8e5e79e6f993019".to_string(),
            },
            target_triple: "aarch64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.11.11%2B20241206-x86_64-unknown-linux-gnu-pgo-full.tar.zst".to_string(),
                sha256: "87abbddbc2e6fe24d5646dda558411a698bdb6b8162d76b2d4cc76c3dcec5365".to_string(),
            },
            target_triple: "x86_64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.11.11%2B20241206-x86_64_v2-unknown-linux-gnu-pgo-full.tar.zst".to_string(),
                sha256: "f6ef3ad31992940ebb42678437664f39088a1f9940228a760925bd90a6abd2b0".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.11.11%2B20241206-x86_64_v3-unknown-linux-gnu-pgo-full.tar.zst".to_string(),
                sha256: "5f8c1ba3d639f878dc4fbfdead99536d31cd6876e2b989d99c9614d8121b20c0".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.12.8%2B20241206-aarch64-unknown-linux-gnu-noopt-full.tar.zst".to_string(),
                sha256: "e4187460f65ef4496b8a93b8c77113c8c9bc46329814c32356a3806b680f94bf".to_string(),
            },
            target_triple: "aarch64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.12.8%2B20241206-x86_64-unknown-linux-gnu-pgo-full.tar.zst".to_string(),
                sha256: "a460f49303af5ea28db631d3e4658e1ae9411f5029008d15ea7af7902e6ef721".to_string(),
            },
            target_triple: "x86_64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.12.8%2B20241206-x86_64_v2-unknown-linux-gnu-pgo-full.tar.zst".to_string(),
                sha256: "0e4806b97dd1089293e6261521f5ec39e805c0f31949010cbd9b866de77b3910".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.12.8%2B20241206-x86_64_v3-unknown-linux-gnu-pgo-full.tar.zst".to_string(),
                sha256: "c8bad9a8ea8014a924d7ebadd619eebcdad168aa336374a4c6bebd1df0e7e77d".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.13.1%2B20241206-aarch64-unknown-linux-gnu-noopt-full.tar.zst".to_string(),
                sha256: "74a0e6d6980c3625f8ed88a3985d98729e5b2308c9c82112ae97a1871152753a".to_string(),
            },
            target_triple: "aarch64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.13.1%2B20241206-x86_64-unknown-linux-gnu-pgo-full.tar.zst".to_string(),
                sha256: "220489b488a8fb7aee766e731cac87290208110820ce97413f66cc0904a486cf".to_string(),
            },
            target_triple: "x86_64-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.13.1%2B20241206-x86_64_v2-unknown-linux-gnu-pgo-full.tar.zst".to_string(),
                sha256: "cc448ae8501baa4a47f8adb28aa0802fcd564d7d85044a2b36e03d844ec4e954".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.13.1%2B20241206-x86_64_v3-unknown-linux-gnu-pgo-full.tar.zst".to_string(),
                sha256: "c81ab5fcbf3b935b016510baa90ad39266b930bb3e43af8620ecb122d3e04a2d".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-gnu".to_string(),
            supports_prebuilt_extension_modules: true,
        },

        // Linux musl.
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.9.21%2B20241206-x86_64-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "8dd0cb2255d4c6a23fec02ae4ca8bbefc738323b7e0b7ae16595c544290bd703".to_string(),
            },
            target_triple: "x86_64-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: false,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.9.21%2B20241206-x86_64_v2-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "f5a310550a6994ccfc4042bcc13366c7acb004220aefabbfc44a36da306abd83".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.9.21%2B20241206-x86_64_v3-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "886b4dd9942df34ea81f5d5d64cc8cf4a2695b24cfdb55f58f4e4d0128255df6".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.10.16%2B20241206-x86_64-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "68775009a694879b20e20b3d25d6a2014914fe02aa87f108d5d61e85395a714f".to_string(),
            },
            target_triple: "x86_64-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: false,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.10.16%2B20241206-x86_64_v2-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "f0543d64fc5cf369730663b3d91cdce058494e6e8f4a6507e265eb1f271af588".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.10.16%2B20241206-x86_64_v3-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "ffd5b8f90fd404c4506573efb5f786c260e95ac9bdf131ca4a1b4a9dbb2c6e25".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.11.11%2B20241206-x86_64-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "2bc8badc637f4fd6cf0227ef00fae6d3cab7bf75481eca24f2b70b6ba8b11cf4".to_string(),
            },
            target_triple: "x86_64-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: false,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.11.11%2B20241206-x86_64_v2-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "27829ca257d0bb3dc30823fdfc0fb23ca83bc58f078eec815c434223c48fc7f0".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.11.11%2B20241206-x86_64_v3-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "49497f4da04ae75ccc759f52408c76376f0c26f115d91b23a075b2a0cb9a0a7b".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.12.8%2B20241206-x86_64-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "d73b947eb73aab7e016406b9be90337c05847e9fb5c221325b3e8dfe18e58c81".to_string(),
            },
            target_triple: "x86_64-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: false,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.12.8%2B20241206-x86_64_v2-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "5f7ccd0d6073ab31849613ad7eff1d1f6633f81db371895b628882c9c78c46c3".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.12.8%2B20241206-x86_64_v3-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "2e916d9cf5040f1aa4c922db8185288698b7896783af53d7490282854283734e".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.13.1%2B20241206-x86_64-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "190ad5d7519913858ee198ceeedba5d93781c7cab5a95eca52d57d7dcfd520a5".to_string(),
            },
            target_triple: "x86_64-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: false,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.13.1%2B20241206-x86_64_v2-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "f4bca57123d79dc0e84e2c2571e93b1c9f5bae5ba9a74168a3471621c65fa227".to_string(),
            },
            target_triple: "x86_64_v2-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.13.1%2B20241206-x86_64_v3-unknown-linux-musl-noopt-full.tar.zst".to_string(),
                sha256: "a9d7105e2da0f5b05a3bc235f5ae1bb4ce503e8cbedf9b9b8d6ea64f9a0b7704".to_string(),
            },
            target_triple: "x86_64_v3-unknown-linux-musl".to_string(),
            supports_prebuilt_extension_modules: true,
        },

        // The order here is important because we will choose the
        // first one. We prefer shared distributions on Windows because
        // they are more versatile: statically linked Windows distributions
        // don't declspec(dllexport) Python symbols and can't load shared
        // shared library Python extensions, making them a pain to work
        // with.

        // Windows shared.
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.9.21%2B20241206-i686-pc-windows-msvc-shared-pgo-full.tar.zst".to_string(),
                sha256: "8bd4428d7da08dd0a9e50820c8dd27a814d41776ed31c40a2c6dec46399a22cc".to_string(),
            },
            target_triple: "i686-pc-windows-msvc".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.10.16%2B20241206-i686-pc-windows-msvc-shared-pgo-full.tar.zst".to_string(),
                sha256: "667edbcf1f1e26fb6b4e29f3b199294425e25c46f7b31e563c11015252396241".to_string(),
            },
            target_triple: "i686-pc-windows-msvc".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.11.11%2B20241206-i686-pc-windows-msvc-shared-pgo-full.tar.zst".to_string(),
                sha256: "e82e3ede645d3434c22db0ab3f6cc1aa287217f8e0803707eaaa12f401ac5b79".to_string(),
            },
            target_triple: "i686-pc-windows-msvc".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.12.8%2B20241206-i686-pc-windows-msvc-shared-pgo-full.tar.zst".to_string(),
                sha256: "b14c6f94b6f7d3fe57edb22ec1ed6dc5acee15e7b3dc15af8f49d725fd75bdd8".to_string(),
            },
            target_triple: "i686-pc-windows-msvc".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.13.1%2B20241206-i686-pc-windows-msvc-shared-pgo-full.tar.zst".to_string(),
                sha256: "e4b0d9bfa0b8ecfc04625b530e58be0ff4ddcc9ce0c1ab3e509224ee6b362923".to_string(),
            },
            target_triple: "i686-pc-windows-msvc".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.9.21%2B20241206-x86_64-pc-windows-msvc-shared-pgo-full.tar.zst".to_string(),
                sha256: "0a8953af66e3cf2ea4124a22e01c62940797ad3d39ce27bf9a96b2f41c7e4777".to_string(),
            },
            target_triple: "x86_64-pc-windows-msvc".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.10.16%2B20241206-x86_64-pc-windows-msvc-shared-pgo-full.tar.zst".to_string(),
                sha256: "c1e5fe4b45ae5dd833c849dee20d91ca12b6dee2666fbfc344741bb59fe1fbf1".to_string(),
            },
            target_triple: "x86_64-pc-windows-msvc".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.11.11%2B20241206-x86_64-pc-windows-msvc-shared-pgo-full.tar.zst".to_string(),
                sha256: "fc63b4dd0778536dbc171b121e1e1c6d6159d09f3f6a1ec4490c5ae958752888".to_string(),
            },
            target_triple: "x86_64-pc-windows-msvc".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.12.8%2B20241206-x86_64-pc-windows-msvc-shared-pgo-full.tar.zst".to_string(),
                sha256: "7b4e910a414291389c5ec277abc532d7c09b158b5ec6ecb0e91920a193675eba".to_string(),
            },
            target_triple: "x86_64-pc-windows-msvc".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.13.1%2B20241206-x86_64-pc-windows-msvc-shared-pgo-full.tar.zst".to_string(),
                sha256: "3a97cd23c8470f3dc340538f3287cec8df8d168e3da67e4435d7697f5f57fc41".to_string(),
            },
            target_triple: "x86_64-pc-windows-msvc".to_string(),
            supports_prebuilt_extension_modules: true,
        },

        // Windows static.
        // DEPRECATED

        // macOS.
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.9.21%2B20241206-aarch64-apple-darwin-pgo-full.tar.zst".to_string(),
                sha256: "4720f80fdcc1c95e6502c7e758312d7581fdeb5be99c0b4948199d63fb3bd062".to_string(),
            },
            target_triple: "aarch64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.10.16%2B20241206-aarch64-apple-darwin-pgo-full.tar.zst".to_string(),
                sha256: "1529ebbcd38a423c571deb58032b90b183e2087fb95aae9d9176884af4e4aae8".to_string(),
            },
            target_triple: "aarch64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.11.11%2B20241206-aarch64-apple-darwin-pgo-full.tar.zst".to_string(),
                sha256: "9c75c8962e91fe5ffe07fdbf26eae465736e46fbc161486d3b14dc9a4eaecabe".to_string(),
            },
            target_triple: "aarch64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.12.8%2B20241206-aarch64-apple-darwin-pgo-full.tar.zst".to_string(),
                sha256: "afb07ad9890b5dcca4694ae2764a37b60277940b0ecc1158981e92455faeccc9".to_string(),
            },
            target_triple: "aarch64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.13.1%2B20241206-aarch64-apple-darwin-pgo-full.tar.zst".to_string(),
                sha256: "343159531c6298f4ac4d86c143f1b7f53eabf53b4ce4d91d57cab238c9403e10".to_string(),
            },
            target_triple: "aarch64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.9".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.9.21%2B20241206-x86_64-apple-darwin-pgo-full.tar.zst".to_string(),
                sha256: "64bb1b6536f416f548a3349a5de6b5cec8b8f09e9457f78fb5bf523dd906a357".to_string(),
            },
            target_triple: "x86_64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.10".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.10.16%2B20241206-x86_64-apple-darwin-pgo-full.tar.zst".to_string(),
                sha256: "f1caa4d5a8533c27cfaa73b740b2e3cc1cce9e5d3fd5b53503abc47defafb036".to_string(),
            },
            target_triple: "x86_64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.11".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.11.11%2B20241206-x86_64-apple-darwin-pgo-full.tar.zst".to_string(),
                sha256: "dd79dcafc74b7b9beff3436a643d23607b462aa1954b022dd898f20f309f36b1".to_string(),
            },
            target_triple: "x86_64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.12".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.12.8%2B20241206-x86_64-apple-darwin-pgo-full.tar.zst".to_string(),
                sha256: "5689f114ec3df9905576dbe18cb3ae5c488339637270e6b71f9690be1d36554c".to_string(),
            },
            target_triple: "x86_64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
        PythonDistributionRecord {
            python_major_minor_version: "3.13".to_string(),
            location: PythonDistributionLocation::Url {
                url: "https://github.com/astral-sh/python-build-standalone/releases/download/20241206/cpython-3.13.1%2B20241206-x86_64-apple-darwin-pgo-full.tar.zst".to_string(),
                sha256: "a2cf9ae6300f1a0f11e504c40e36ccfa2c3469d9a321307c2b72a0e9bb81569b".to_string(),
            },
            target_triple: "x86_64-apple-darwin".to_string(),
            supports_prebuilt_extension_modules: true,
        },
    ];

    PythonDistributionCollection { dists }
});
